name: WarpGUI
main: ClickedTran\WarpGUI\WarpGUI
api: 4.0.0
version: 1.0.0
author: ClickedTran, NoobMCBG
description: it's a plugin that allows you to navigate using the chest menu

permissions:
  warpgui.command.setwarp:
    description: Permission add warp
    default: op
  warpgui.command.editwarp:
    description: Permission edit warp
    default: op
  warpgui.command.deletewarp:
    description: Permission delete warp
    default: op
  warpgui.command.help:
    description: Permission help all commands warp
    default: op
  warpgui.command:
    description: Permission use command /warpgui
    default: true
